repository_type: pipeline

nf_core_version: 3.1.2

lint:
  files_unchanged:
    - .github/CONTRIBUTING.md
    - .prettierignore
    - .prettierignore
    - .prettierignore
    - .github/CONTRIBUTING.md
    - .prettierignore
    - .prettierignore
    - .prettierignore
    - CODE_OF_CONDUCT.md
    - assets/nf-core-zfvarmerge_logo_light.png
    - docs/images/nf-core-zfvarmerge_logo_light.png
    - docs/images/nf-core-zfvarmerge_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
  nextflow_config:
    - manifest.name
    - manifest.homePage
    - validation.help.beforeText
    - validation.help.afterText
    - validation.summary.beforeText
    - validation.summary.afterText
  multiqc_config:
    - report_comment
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - assets/email_template.html
    - assets/sendmail_template.txt
    - assets/email_template.txt
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - assets/email_template.html
    - assets/sendmail_template.txt
    - assets/email_template.txt
    - CODE_OF_CONDUCT.md
    - assets/nf-core-zfvarmerge_logo_light.png
    - docs/images/nf-core-zfvarmerge_logo_light.png
    - docs/images/nf-core-zfvarmerge_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
  readme:
    - nextflow_badge

template:
  org: iansealy
  name: zfvarmerge
  description: Zebrafish variant merging
  author: Ian Sealy
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features:
    - igenomes
    - github_badges
    - gitpod
    - codespaces
    - fastqc
    - email
    - adaptivecard
    - seqera_platform
    - rocrate
    - vscode
  is_nfcore: false
